### ISSUE TITLE
How to config a enum property in a domain

### ISSUE THREAD

**Issue by sunyuyangg555** [metawidget/metawidget#52]
Hi, I am learning metawidget framework.
I have copied addressbook to [https://github.com/sunyuyangg555/metawidgetdemo/tree/develop](url), I  only change to build to gradle.
I have run successfully! But when I search contacts, I encounter a problem:

`Exception in thread "AWT-EventQueue-0" org.metawidget.widgetprocessor.iface.WidgetProcessorException: java.lang.reflect.InvocationTargetException
	at org.metawidget.widgetprocessor.iface.WidgetProcessorException.newException(WidgetProcessorException.java:42)
	at org.metawidget.swing.widgetprocessor.binding.reflection.ReflectionBindingProcessor$BoundAction.actionPerformed(ReflectionBindingProcessor.java:265)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.metawidget.swing.widgetprocessor.binding.reflection.ReflectionBindingProcessor$BoundAction.actionPerformed(ReflectionBindingProcessor.java:260)
	... 36 more
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to at.jiffy.share.model.ContactType
	at at.jiffy.addressbook.AddressBook.search(AddressBook.java:146)
	... 41 more`

according to the error message, type of ContactType is enum, I can not do: 

`mContactSearch.setType((ContactType) mSearchMetawidget.getValue("type"));`  

and  as well as saving a contact with a Gender .
How do I fix it?

**Comment by kennardconsulting** [comment]
The Metawidget in that example is configured by this file:

https://github.com/metawidget/metawidget/blob/master/examples/java/swing/addressbook/src/main/resources/org/metawidget/example/swing/addressbook/metawidget.xml

Make sure you have that config. It needs to hook in BeansBindingProcessor for the enum support.

**Comment by sunyuyangg555** [comment]
Hi, thank you for your reply!
I have add 2 converter like this:
```xml
<beansBindingProcessor xmlns="java:org.metawidget.swing.widgetprocessor.binding.beansbinding"
                                       config="BeansBindingProcessorConfig">
                    <converter>
                        <class>java.util.Date</class>
                        <class>java.lang.String</class>
                        <dateConverter xmlns="java:at.jiffy.addressbook.converter"/>
                    </converter>
                    <converter>
                        <class>at.jiffy.share.model.ContactType</class>
                        <class>java.lang.String</class>
                        <ContactTypeConverter xmlns="java:at.jiffy.addressbook.converter"/>
                    </converter>
                    <converter>
                        <class>at.jiffy.share.model.Gender</class>
                        <class>java.lang.String</class>
                        <GenderConverter xmlns="java:at.jiffy.addressbook.converter"/>
                    </converter>
                </beansBindingProcessor>
```
The problem of type conversion seems to have been solved, but I encountered another problem.When I run,the Type drop-down menu shows the same content
![a_pnaqbxt__omenwbv z_un](https://user-images.githubusercontent.com/5210372/34754392-6434fe7c-f5f8-11e7-918e-7ca6f2e3da7c.jpg)

What should I do?

**Comment by kennardconsulting** [comment]
You shouldn't need to change metawidget.xml. The example that is shipped in the examples package already builds and works (albeit using Maven instead of Gradle). Can you confirm that? If it does, then this must be related to the changes you've made in the Gradle build?

**Comment by sunyuyangg555** [comment]
Ok, I will rebuild with maven. Thanks!
